### ISSUE TITLE
Upgrade to gradle 7.3

### ISSUE THREAD

**Issue by AntonOellerer** [DDS-GmbH/poipath#27]
Gradle 7.3 will be the first version to officially support java 17.
It has not been released yet, but should be in a few days/weeks.
https://github.com/gradle/gradle/releases

**Comment by AntonOellerer** [comment]
Available now

**Comment by alexpartsch** [comment]
Upgraded Gradle to `7.5.1` in 83b14c9fa5a4efbbc1310839778a928ced0bb130
